env:
  global:
    - CI_ENV=production

sudo: false
addons:
  apt:
    packages:
      - ncftp

branches:
  only:
    - deploy
before_script:
  - rm -rf .git
  - rm .directory
  - rm readme.md
  - rm contributing.md
  - rm license.txt
  - rm .gitignore
  - rm .editorconfig
  - rm -rf tests

script: ncftpput -R -v -u "$FTP_USER" -p "$FTP_PASS" "$FTP_HOST" /htdocs .
