language: php
dist: trusty
sudo: enabled

branches:
  only:
  - master
  - deploy
 
env:
  - CI_ENV=production
 
before_install:
  - sudo apt-get install lftp

script: 
	- "lftp -c \"open -u $FTP_USER,$FTP_PASS $FTP_HOST; mirror -R . public_html\""
