# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers-legacy

    steps:
      - run: npm install --save-dev ftp-deploy
      - run: node deploy

general:
  branches:
    only:
     - deploy
